create extension if not exists pgcrypto;

create table if not exists public.recibos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  fecha date not null,
  nombre_cliente text not null,
  monto numeric(12, 2) not null check (monto > 0),
  concepto text not null,
  url_archivo text,
  created_at timestamptz not null default now()
);

alter table public.recibos add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.recibos add column if not exists punto_venta text;
alter table public.recibos add column if not exists numero_recibo text;
alter table public.recibos add column if not exists nombre text;
alter table public.recibos add column if not exists apellido text;
alter table public.recibos add column if not exists dni text;
alter table public.recibos add column if not exists importe_letra text;
alter table public.recibos add column if not exists titular_cuenta text;
alter table public.recibos add column if not exists file_name text;
alter table public.recibos add column if not exists drive_url text;
alter table public.recibos alter column user_id set default auth.uid();

create unique index if not exists recibos_numero_unq
on public.recibos (user_id, punto_venta, numero_recibo);

create index if not exists recibos_user_created_at_idx
on public.recibos (user_id, created_at desc);

create table if not exists public.materias (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nombre text not null,
  anio integer not null check (anio between 1 and 10),
  cuatrimestre integer not null check (cuatrimestre between 1 and 4),
  horario text not null,
  aula text not null,
  descripcion text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.alumnos (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  dni text not null,
  nombre text not null,
  apellido text not null,
  email text not null default '',
  telefono text not null default '',
  observaciones text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.materia_alumnos (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  materia_id uuid not null references public.materias(id) on delete cascade,
  alumno_id uuid not null references public.alumnos(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.evaluaciones (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  materia_id uuid not null references public.materias(id) on delete cascade,
  nombre text not null,
  tipo text not null check (tipo in ('parcial', 'tp', 'integrador', 'final', 'otro')),
  fecha date,
  orden integer not null default 0,
  puntaje_maximo numeric(6, 2) not null default 10 check (puntaje_maximo > 0),
  cuenta_pendientes boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.calificaciones (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  evaluacion_id uuid not null references public.evaluaciones(id) on delete cascade,
  alumno_id uuid not null references public.alumnos(id) on delete cascade,
  nota numeric(6, 2) not null check (nota >= 0),
  comentario text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.asistencias (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  materia_id uuid not null references public.materias(id) on delete cascade,
  alumno_id uuid not null references public.alumnos(id) on delete cascade,
  fecha date not null,
  estado text not null check (estado in ('present', 'late', 'absent', 'justified')),
  observaciones text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists alumnos_owner_dni_unq
on public.alumnos (owner_user_id, dni);

create unique index if not exists materia_alumnos_unq
on public.materia_alumnos (materia_id, alumno_id);

create unique index if not exists evaluaciones_materia_nombre_unq
on public.evaluaciones (materia_id, nombre);

create unique index if not exists calificaciones_eval_alumno_unq
on public.calificaciones (evaluacion_id, alumno_id);

create unique index if not exists asistencias_materia_alumno_fecha_unq
on public.asistencias (materia_id, alumno_id, fecha);

create index if not exists materias_owner_idx on public.materias (owner_user_id, anio, cuatrimestre, nombre);
create index if not exists alumnos_owner_idx on public.alumnos (owner_user_id, apellido, nombre);
create index if not exists materia_alumnos_owner_idx on public.materia_alumnos (owner_user_id, materia_id);
create index if not exists evaluaciones_owner_idx on public.evaluaciones (owner_user_id, materia_id, orden);
create index if not exists calificaciones_owner_idx on public.calificaciones (owner_user_id, evaluacion_id);
create index if not exists asistencias_owner_idx on public.asistencias (owner_user_id, materia_id, fecha desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_owner_user_id()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if new.owner_user_id is null then
      new.owner_user_id = auth.uid();
    end if;
  elsif tg_op = 'UPDATE' then
    new.owner_user_id = old.owner_user_id;
  end if;
  return new;
end;
$$;

drop trigger if exists set_updated_at_materias on public.materias;
create trigger set_updated_at_materias
before update on public.materias
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_alumnos on public.alumnos;
create trigger set_updated_at_alumnos
before update on public.alumnos
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_evaluaciones on public.evaluaciones;
create trigger set_updated_at_evaluaciones
before update on public.evaluaciones
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_calificaciones on public.calificaciones;
create trigger set_updated_at_calificaciones
before update on public.calificaciones
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_asistencias on public.asistencias;
create trigger set_updated_at_asistencias
before update on public.asistencias
for each row execute function public.set_updated_at();

drop trigger if exists set_owner_user_id_materias on public.materias;
create trigger set_owner_user_id_materias
before insert on public.materias
for each row execute function public.set_owner_user_id();

drop trigger if exists set_owner_user_id_alumnos on public.alumnos;
create trigger set_owner_user_id_alumnos
before insert on public.alumnos
for each row execute function public.set_owner_user_id();

drop trigger if exists set_owner_user_id_materia_alumnos on public.materia_alumnos;
create trigger set_owner_user_id_materia_alumnos
before insert on public.materia_alumnos
for each row execute function public.set_owner_user_id();

drop trigger if exists set_owner_user_id_evaluaciones on public.evaluaciones;
create trigger set_owner_user_id_evaluaciones
before insert on public.evaluaciones
for each row execute function public.set_owner_user_id();

drop trigger if exists set_owner_user_id_calificaciones on public.calificaciones;
create trigger set_owner_user_id_calificaciones
before insert on public.calificaciones
for each row execute function public.set_owner_user_id();

drop trigger if exists set_owner_user_id_asistencias on public.asistencias;
create trigger set_owner_user_id_asistencias
before insert on public.asistencias
for each row execute function public.set_owner_user_id();

drop trigger if exists preserve_owner_user_id_materias on public.materias;
create trigger preserve_owner_user_id_materias
before update on public.materias
for each row execute function public.set_owner_user_id();

drop trigger if exists preserve_owner_user_id_alumnos on public.alumnos;
create trigger preserve_owner_user_id_alumnos
before update on public.alumnos
for each row execute function public.set_owner_user_id();

drop trigger if exists preserve_owner_user_id_materia_alumnos on public.materia_alumnos;
create trigger preserve_owner_user_id_materia_alumnos
before update on public.materia_alumnos
for each row execute function public.set_owner_user_id();

drop trigger if exists preserve_owner_user_id_evaluaciones on public.evaluaciones;
create trigger preserve_owner_user_id_evaluaciones
before update on public.evaluaciones
for each row execute function public.set_owner_user_id();

drop trigger if exists preserve_owner_user_id_calificaciones on public.calificaciones;
create trigger preserve_owner_user_id_calificaciones
before update on public.calificaciones
for each row execute function public.set_owner_user_id();

drop trigger if exists preserve_owner_user_id_asistencias on public.asistencias;
create trigger preserve_owner_user_id_asistencias
before update on public.asistencias
for each row execute function public.set_owner_user_id();

alter table public.recibos enable row level security;
alter table public.materias enable row level security;
alter table public.alumnos enable row level security;
alter table public.materia_alumnos enable row level security;
alter table public.evaluaciones enable row level security;
alter table public.calificaciones enable row level security;
alter table public.asistencias enable row level security;

drop policy if exists "recibos_select_own" on public.recibos;
create policy "recibos_select_own"
on public.recibos
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "recibos_insert_own" on public.recibos;
create policy "recibos_insert_own"
on public.recibos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "recibos_update_own" on public.recibos;
create policy "recibos_update_own"
on public.recibos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "materias_select_own" on public.materias;
create policy "materias_select_own"
on public.materias
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "materias_insert_own" on public.materias;
create policy "materias_insert_own"
on public.materias
for insert
to authenticated
with check (auth.role() = 'authenticated');

drop policy if exists "materias_update_own" on public.materias;
create policy "materias_update_own"
on public.materias
for update
to authenticated
using (auth.role() = 'authenticated' and owner_user_id = auth.uid())
with check (auth.role() = 'authenticated');

drop policy if exists "materias_delete_own" on public.materias;
create policy "materias_delete_own"
on public.materias
for delete
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "alumnos_select_own" on public.alumnos;
create policy "alumnos_select_own"
on public.alumnos
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "alumnos_insert_own" on public.alumnos;
create policy "alumnos_insert_own"
on public.alumnos
for insert
to authenticated
with check (auth.role() = 'authenticated');

drop policy if exists "alumnos_update_own" on public.alumnos;
create policy "alumnos_update_own"
on public.alumnos
for update
to authenticated
using (auth.role() = 'authenticated' and owner_user_id = auth.uid())
with check (auth.role() = 'authenticated');

drop policy if exists "alumnos_delete_own" on public.alumnos;
create policy "alumnos_delete_own"
on public.alumnos
for delete
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "materia_alumnos_select_own" on public.materia_alumnos;
create policy "materia_alumnos_select_own"
on public.materia_alumnos
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "materia_alumnos_insert_own" on public.materia_alumnos;
create policy "materia_alumnos_insert_own"
on public.materia_alumnos
for insert
to authenticated
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.materias
    where id = materia_id and owner_user_id = auth.uid()
  )
  and exists (
    select 1
    from public.alumnos
    where id = alumno_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "materia_alumnos_delete_own" on public.materia_alumnos;
create policy "materia_alumnos_delete_own"
on public.materia_alumnos
for delete
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "evaluaciones_select_own" on public.evaluaciones;
create policy "evaluaciones_select_own"
on public.evaluaciones
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "evaluaciones_insert_own" on public.evaluaciones;
create policy "evaluaciones_insert_own"
on public.evaluaciones
for insert
to authenticated
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.materias
    where id = materia_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "evaluaciones_update_own" on public.evaluaciones;
create policy "evaluaciones_update_own"
on public.evaluaciones
for update
to authenticated
using (auth.role() = 'authenticated' and owner_user_id = auth.uid())
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.materias
    where id = materia_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "evaluaciones_delete_own" on public.evaluaciones;
create policy "evaluaciones_delete_own"
on public.evaluaciones
for delete
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "calificaciones_select_own" on public.calificaciones;
create policy "calificaciones_select_own"
on public.calificaciones
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "calificaciones_insert_own" on public.calificaciones;
create policy "calificaciones_insert_own"
on public.calificaciones
for insert
to authenticated
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.evaluaciones
    where id = evaluacion_id and owner_user_id = auth.uid()
  )
  and exists (
    select 1
    from public.alumnos
    where id = alumno_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "calificaciones_update_own" on public.calificaciones;
create policy "calificaciones_update_own"
on public.calificaciones
for update
to authenticated
using (auth.role() = 'authenticated' and owner_user_id = auth.uid())
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.evaluaciones
    where id = evaluacion_id and owner_user_id = auth.uid()
  )
  and exists (
    select 1
    from public.alumnos
    where id = alumno_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "calificaciones_delete_own" on public.calificaciones;
create policy "calificaciones_delete_own"
on public.calificaciones
for delete
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "asistencias_select_own" on public.asistencias;
create policy "asistencias_select_own"
on public.asistencias
for select
to authenticated
using (auth.uid() = owner_user_id);

drop policy if exists "asistencias_insert_own" on public.asistencias;
create policy "asistencias_insert_own"
on public.asistencias
for insert
to authenticated
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.materias
    where id = materia_id and owner_user_id = auth.uid()
  )
  and exists (
    select 1
    from public.alumnos
    where id = alumno_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "asistencias_update_own" on public.asistencias;
create policy "asistencias_update_own"
on public.asistencias
for update
to authenticated
using (auth.role() = 'authenticated' and owner_user_id = auth.uid())
with check (
  auth.role() = 'authenticated'
  and exists (
    select 1
    from public.materias
    where id = materia_id and owner_user_id = auth.uid()
  )
  and exists (
    select 1
    from public.alumnos
    where id = alumno_id and owner_user_id = auth.uid()
  )
);

drop policy if exists "asistencias_delete_own" on public.asistencias;
create policy "asistencias_delete_own"
on public.asistencias
for delete
to authenticated
using (auth.uid() = owner_user_id);

comment on table public.recibos is 'Historial de recibos emitidos desde la app privada de Sion.';
comment on table public.materias is 'Materias creadas por cada profesor autenticado.';
comment on table public.alumnos is 'Base privada de alumnos cargada por cada profesor.';
comment on table public.materia_alumnos is 'Inscripciones de alumnos a materias por profesor.';
comment on table public.evaluaciones is 'Columnas dinámicas de calificaciones por materia.';
comment on table public.calificaciones is 'Notas cargadas por evaluación y alumno.';
comment on table public.asistencias is 'Registro de asistencia por fecha, materia y alumno.';
